// AUTO-GENERATED by scripts/generate_types.py — DO NOT EDIT (A20/DEC-006).
// 무의존 JSON-Schema(부분집합) 검증기: 왕복 테스트의 TS(Node)측 단계.
// 사용: node validate_roundtrip.mjs <instances.json>
//   instances.json = {"ModelName": {...instance...}, ...}
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemaDir = join(here, "json_schema");

function checkType(v, t) {
  switch (t) {
    case "string": return typeof v === "string";
    case "integer": return typeof v === "number" && Number.isInteger(v);
    case "number": return typeof v === "number";
    case "boolean": return typeof v === "boolean";
    case "array": return Array.isArray(v);
    case "object": return v !== null && typeof v === "object" && !Array.isArray(v);
    case "null": return v === null;
    default: return true;
  }
}

function validate(value, schema, path, errors) {
  if (!schema || Object.keys(schema).length === 0) return;
  if (schema.anyOf) {
    const pre = errors.length;
    for (const sub of schema.anyOf) {
      const trial = [];
      validate(value, sub, path, trial);
      if (trial.length === 0) return;
    }
    errors.push(`${path}: anyOf 전 분기 불일치`);
    return;
  }
  if (schema.enum && !schema.enum.includes(value)) {
    errors.push(`${path}: enum 위반 (${JSON.stringify(value)})`);
    return;
  }
  if (schema.type && !checkType(value, schema.type)) {
    errors.push(`${path}: 타입 ${schema.type} 위반`);
    return;
  }
  if (schema.type === "number" || schema.type === "integer") {
    if (schema.minimum !== undefined && value < schema.minimum) errors.push(`${path}: minimum 위반`);
    if (schema.maximum !== undefined && value > schema.maximum) errors.push(`${path}: maximum 위반`);
  }
  if (schema.type === "array" && schema.items) {
    value.forEach((item, i) => validate(item, schema.items, `${path}[${i}]`, errors));
  }
  if (schema.type === "object" && schema.properties) {
    for (const req of schema.required ?? []) {
      if (!(req in value)) errors.push(`${path}.${req}: 필수 필드 누락`);
    }
    for (const [k, v] of Object.entries(value)) {
      if (k in schema.properties) {
        validate(v, schema.properties[k], `${path}.${k}`, errors);
      } else if (schema.additionalProperties === false) {
        errors.push(`${path}.${k}: additionalProperties=false 위반 (extra='forbid')`);
      }
    }
  }
}

const instances = JSON.parse(readFileSync(process.argv[2], "utf-8"));
const available = new Set(readdirSync(schemaDir).map((f) => f.replace(".schema.json", "")));
let failed = 0;
const out = {};
for (const [name, instance] of Object.entries(instances)) {
  if (!available.has(name)) { console.error(`SKIP ${name}: 스키마 파일 없음`); failed++; continue; }
  const schema = JSON.parse(readFileSync(join(schemaDir, `${name}.schema.json`), "utf-8"));
  const errors = [];
  validate(instance, schema, name, errors);
  if (errors.length) { failed++; console.error(`FAIL ${name}:\n  ` + errors.join("\n  ")); }
  out[name] = instance; // TS측 통과 인스턴스를 그대로 반환 (Python 재파싱 입력)
}
if (failed) { console.error(`TS-side validation FAILED: ${failed}`); process.exit(1); }
console.log(JSON.stringify(out));
