// AUTO-GENERATED by scripts/generate_types.py — DO NOT EDIT (A20/DEC-006).
// 정본: backend/vamos_core/schemas/contracts.py (Pydantic v2). 변경은 Pydantic에서 시작.
import { z } from "zod";

export const IntentFrameSchema = z.object({
  intent_id: z.string(),
  trace_id: z.string(),
  timestamp: z.string(),
  user_goal: z.string(),
  task_type: z.enum(["explain", "plan", "code", "research", "summarize", "design", "debug", "etc"]),
  domain_hint: z.record(z.any()),
  constraints: z.record(z.any()),
  risk_flags: z.record(z.any()),
  ambiguity: z.record(z.any()),
  required_artifacts: z.array(z.string()),
}).strict();  // extra='forbid'
export type IntentFrame = z.infer<typeof IntentFrameSchema>;

export const EvidencePackSchema = z.object({
  evidence_pack_id: z.string(),
  trace_id: z.string(),
  timestamp: z.string(),
  items: z.array(z.record(z.any())),
  coverage: z.record(z.any()),
  citations_ready: z.boolean(),
}).strict();  // extra='forbid'
export type EvidencePack = z.infer<typeof EvidencePackSchema>;

export const DecisionSchemaSchema = z.object({
  decision_id: z.string(),
  trace_id: z.string(),
  timestamp: z.string(),
  intent_frame_ref: z.string(),
  evidence_pack_ref: z.string(),
  policy_gate: z.enum(["block", "require_approval", "mask", "allow"]),
  approval_required: z.boolean(),
  approval_status: z.enum(["approved", "denied"]),
  cost_gate: z.enum(["normal", "downshift", "split", "stop"]),
  routing: z.record(z.any()),
  memory_plan: z.record(z.any()),
  output_spec: z.record(z.any()),
  conclusion: z.enum(["ACCEPT", "REJECT", "HOLD", "ESCALATE"]),
  locked: z.boolean(),
  optional_signals: z.array(z.record(z.any())).nullable().optional(),
  verify: z.record(z.any()).nullable().optional(),
  gates: z.record(z.any()).nullable().optional(),
  s_module_hints: z.record(z.any()).nullable().optional(),
  confidence_score: z.number().min(0.0).max(1.0),
  confidence_level: z.enum(["HIGH", "MEDIUM", "LOW", "REFUSE"]),
}).strict();  // extra='forbid'
export type DecisionSchema = z.infer<typeof DecisionSchemaSchema>;

export const LogEventSchemaSchema = z.object({
  event_type: z.string(),
  producer: z.string(),
  when: z.string(),
  payload: z.record(z.any()),
  severity: z.enum(["info", "warn", "error", "critical"]),
  sinks: z.array(z.string()).nullable().optional(),
  links: z.record(z.any()).nullable().optional(),
}).strict();  // extra='forbid'
export type LogEventSchema = z.infer<typeof LogEventSchemaSchema>;

export const ResponseEnvelopeSchema = z.object({
  answer: z.record(z.any()),
  evidence: z.record(z.any()),
  self_check: z.record(z.any()),
  decision_ref: z.record(z.any()),
  audit: z.record(z.any()),
}).strict();  // extra='forbid'
export type ResponseEnvelope = z.infer<typeof ResponseEnvelopeSchema>;

export const StructuredOutputSchema = z.object({
  artifact_type: z.enum(["md", "json", "code", "diagram", "etc"]),
  content: z.string(),
  compliance_report: z.record(z.any()),
  artifact_meta: z.record(z.any()),
}).strict();  // extra='forbid'
export type StructuredOutput = z.infer<typeof StructuredOutputSchema>;

export const MemoryRecordSchema = z.object({
  record_id: z.string(),
  project_id: z.string(),
  scope: z.enum(["L0", "L1", "L2", "L3"]),
  memory_type: z.enum(["B-1", "B-2", "B-3", "B-4"]),
  content_summary: z.string(),
  created_at: z.string(),
  policy_decision: z.enum(["allow", "restrict", "deny"]),
  ttl: z.string().nullable().optional(),
  tags: z.array(z.string()).nullable().optional(),
  source_refs: z.array(z.string()).nullable().optional(),
  masked: z.boolean().nullable().optional(),
  activation_state: z.enum(["draft", "approved", "active", "deprecated"]).nullable().optional(),
  version: z.string().nullable().optional(),
  procedure_id: z.string().nullable().optional(),
  target_scope: z.enum(["global", "project"]).nullable().optional(),
  trigger_conditions: z.string().nullable().optional(),
  steps: z.array(z.string()).nullable().optional(),
  required_tools: z.array(z.string()).nullable().optional(),
  safety_notes: z.string().nullable().optional(),
  provenance: z.record(z.any()).nullable().optional(),
}).strict();  // extra='forbid'
export type MemoryRecord = z.infer<typeof MemoryRecordSchema>;

export const SourceQoDSchema = z.object({
  source_id: z.string(),
  project_id: z.string(),
  qod_score: z.number().min(0.0).max(1.0),
  freshness: z.number().min(0.0).max(1.0),
  reliability: z.number().min(0.0).max(1.0),
  completeness: z.number().min(0.0).max(1.0),
  computed_at: z.string(),
  scope: z.enum(["L0", "L1", "L2", "L3"]).nullable().optional(),
}).strict();  // extra='forbid'
export type SourceQoD = z.infer<typeof SourceQoDSchema>;

export const PolicyCheckSchema = z.object({
  check_id: z.string(),
  decision: z.enum(["deny", "restrict", "allow"]),
  reasons: z.array(z.string()),
  rule_refs: z.array(z.string()),
  detected_sensitive_types: z.array(z.enum(["PII", "AUTH", "MEDICAL", "LEGAL"])),
  fallback_id: z.string().nullable().optional(),
  required_approval_id: z.string().nullable().optional(),
}).strict();  // extra='forbid'
export type PolicyCheck = z.infer<typeof PolicyCheckSchema>;

export const ApprovalSchemaSchema = z.object({
  approval_id: z.string(),
  approval_stage: z.enum(["plan", "execute"]),
  requester: z.string(),
  scope: z.enum(["domain", "cost", "policy", "external_action", "storage"]),
  description: z.string(),
  expires_at: z.string(),
  status: z.enum(["approved", "denied"]),
  decided_by: z.string(),
  risk_level: z.enum(["P0", "P1", "P2"]).nullable().optional(),
  cost_snapshot: z.record(z.any()).nullable().optional(),
  policy_snapshot: z.record(z.any()).nullable().optional(),
  audit_trace_id: z.string().nullable().optional(),
}).strict();  // extra='forbid'
export type ApprovalSchema = z.infer<typeof ApprovalSchemaSchema>;

export const CostBudgetSchema = z.object({
  budget_id: z.string(),
  mode: z.enum(["V1", "V2", "V3"]),
  daily_limit: z.number().int(),
  monthly_limit: z.number().int(),
  used_today: z.number().int(),
  used_month: z.number().int(),
  forecast: z.number().nullable().optional(),
  actual: z.number().nullable().optional(),
  block_on_exceed: z.boolean().nullable().optional(),
}).strict();  // extra='forbid'
export type CostBudget = z.infer<typeof CostBudgetSchema>;

export const DownshiftSchemaSchema = z.object({
  warn_threshold_percent: z.number().int(),
  block_threshold_percent: z.number().int(),
  trigger_type: z.enum(["daily", "monthly"]),
  near_action: z.enum(["warn", "force_mini"]),
  exceed_action: z.literal("block"),
  main_requires_approval: z.boolean(),
}).strict();  // extra='forbid'
export type DownshiftSchema = z.infer<typeof DownshiftSchemaSchema>;

export const NodeCapabilityProfileSchema = z.object({
  node_id: z.string(),
  required_tools: z.array(z.string()),
  risk_class: z.enum(["low", "med", "high"]),
  cost_class: z.enum(["v0", "v1", "v2", "v3"]),
  required_gates: z.array(z.enum(["policy", "cost", "approval", "evidence", "self_check"])),
  optional_tools: z.array(z.string()).nullable().optional(),
}).strict();  // extra='forbid'
export type NodeCapabilityProfile = z.infer<typeof NodeCapabilityProfileSchema>;

export const NodeRequestEnvelopeSchema = z.object({
  request_id: z.string(),
  project_id: z.string(),
  session_id: z.string(),
  node_id: z.string(),
  intent_summary: z.string(),
  constraints: z.record(z.any()),
  trace_id: z.string(),
  policy_snapshot_id: z.string().nullable().optional(),
  budget_snapshot_id: z.string().nullable().optional(),
  evidence_refs: z.array(z.string()).nullable().optional(),
  decision_id: z.string().nullable().optional(),
  ui_hints: z.record(z.any()).nullable().optional(),
}).strict();  // extra='forbid'
export type NodeRequestEnvelope = z.infer<typeof NodeRequestEnvelopeSchema>;

export const NodeResponseEnvelopeSchema = z.object({
  trace_id: z.string(),
  node_id: z.string(),
  domain: z.string(),
  inputs: z.record(z.any()),
  outputs: z.record(z.any()),
  status: z.enum(["success", "fail"]),
}).strict();  // extra='forbid'
export type NodeResponseEnvelope = z.infer<typeof NodeResponseEnvelopeSchema>;

export const ToolCallRegistrySchema = z.object({
  tool_id: z.string(),
  node_id: z.string(),
  risk_class: z.enum(["low", "med", "high"]),
  auth_method: z.enum(["none", "api_key", "oauth2", "mcp_token"]),
  enabled: z.boolean(),
  mcp_endpoint: z.string().nullable().optional(),
  rate_limit: z.record(z.any()).nullable().optional(),
}).strict();  // extra='forbid'
export type ToolCallRegistry = z.infer<typeof ToolCallRegistrySchema>;

export const MCPBridgeLayerSchema = z.object({
  bridge_id: z.string(),
  node_id: z.string(),
  transport: z.literal("streamable_http"),
  base_url: z.string(),
  discovered_tools: z.array(z.string()).nullable().optional(),
  auth_config: z.record(z.any()).nullable().optional(),
  health_check_interval_sec: z.number().int().nullable().optional(),
}).strict();  // extra='forbid'
export type MCPBridgeLayer = z.infer<typeof MCPBridgeLayerSchema>;

export const ToolRegistryEntrySchema = z.object({
  tool_id: z.string(),
  category: z.string(),
  adapter_id: z.string(),
  risk_class: z.enum(["low", "med", "high"]),
  cost_class: z.enum(["v0", "v1", "v2", "v3"]),
  required_gates: z.array(z.enum(["policy", "cost", "approval", "evidence", "self_check"])),
  outputs: z.array(z.enum(["signal", "artifact", "memory", "log"])).nullable().optional(),
  notes: z.string().nullable().optional(),
}).strict();  // extra='forbid'
export type ToolRegistryEntry = z.infer<typeof ToolRegistryEntrySchema>;

export const BrainAdapterResponseSchema = z.object({
  output_text: z.string(),
  evidence_summary: z.string(),
  cost_used_estimate: z.record(z.any()),
  warnings: z.array(z.string()),
  trace_id: z.string(),
  tool_calls: z.array(z.record(z.any())).nullable().optional(),
  qod_hint: z.record(z.any()).nullable().optional(),
}).strict();  // extra='forbid'
export type BrainAdapterResponse = z.infer<typeof BrainAdapterResponseSchema>;

export const WorkflowStageSchema = z.object({
  stage_id: z.enum(["intake", "plan", "execute", "verify", "deliver"]),
  stage_name: z.string(),
  description: z.string(),
  sub_stages: z.array(z.any()).nullable().optional(),
}).strict();  // extra='forbid'
export type WorkflowStage = z.infer<typeof WorkflowStageSchema>;

export const WorkflowOutputSchema = z.object({
  user_response: z.string(),
  evidence_summary: z.string(),
  log_report: z.record(z.any()),
}).strict();  // extra='forbid'
export type WorkflowOutput = z.infer<typeof WorkflowOutputSchema>;

export const FailureReportSchema = z.object({
  failure_cause: z.string(),
  evidence_gap: z.string(),
  risk_detected: z.record(z.any()),
  improvement_hint: z.string(),
}).strict();  // extra='forbid'
export type FailureReport = z.infer<typeof FailureReportSchema>;

export const GuardrailsCheckSchema = z.object({
  check_id: z.string(),
  trace_id: z.string(),
  layer1_nemo: z.record(z.any()),
  layer2_guardrails_ai: z.record(z.any()),
  layer3_llamaguard: z.record(z.any()),
  overall_decision: z.enum(["allow", "restrict", "deny"]),
  blocked_by: z.enum(["layer1", "layer2", "layer3"]).nullable().optional(),
}).strict();  // extra='forbid'
export type GuardrailsCheck = z.infer<typeof GuardrailsCheckSchema>;

export const RBACRoleSchema = z.object({
  role: z.enum(["OWNER", "ADMIN", "OPERATOR", "VIEWER"]),
  permissions: z.array(z.string()),
  description: z.string(),
  max_autonomy_level: z.enum(["L0", "L1", "L2", "L3"]),
  p2_access: z.boolean(),
  cost_approval_limit: z.number().int().nullable().optional(),
}).strict();  // extra='forbid'
export type RBACRole = z.infer<typeof RBACRoleSchema>;

export const AutonomyLevelSchemaSchema = z.object({
  level: z.enum(["L0", "L1", "L2", "L3"]),
  name: z.string(),
  description: z.string(),
  auto_execute: z.boolean(),
  notification_required: z.boolean(),
  approval_required: z.boolean(),
  allowed_domains: z.array(z.string()).nullable().optional(),
}).strict();  // extra='forbid'
export type AutonomyLevelSchema = z.infer<typeof AutonomyLevelSchemaSchema>;
