// AUTO-GENERATED by scripts/generate_types.py — DO NOT EDIT (A20/DEC-006).
// 정본: backend/vamos_core/schemas/contracts.py (Pydantic v2). 변경은 Pydantic에서 시작.
// deny_unknown_fields = Pydantic extra='forbid' 등가 (A20 규칙 2).
#![allow(non_snake_case, dead_code)]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct IntentFrame {
    pub intent_id: String,
    pub trace_id: String,
    pub timestamp: String,
    pub user_goal: String,
    pub task_type: String,
    pub domain_hint: serde_json::Value,
    pub constraints: serde_json::Value,
    pub risk_flags: serde_json::Value,
    pub ambiguity: serde_json::Value,
    pub required_artifacts: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct EvidencePack {
    pub evidence_pack_id: String,
    pub trace_id: String,
    pub timestamp: String,
    pub items: Vec<serde_json::Value>,
    pub coverage: serde_json::Value,
    pub citations_ready: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct DecisionSchema {
    pub decision_id: String,
    pub trace_id: String,
    pub timestamp: String,
    pub intent_frame_ref: String,
    pub evidence_pack_ref: String,
    pub policy_gate: String,
    pub approval_required: bool,
    pub approval_status: String,
    pub cost_gate: String,
    pub routing: serde_json::Value,
    pub memory_plan: serde_json::Value,
    pub output_spec: serde_json::Value,
    pub conclusion: String,
    pub locked: bool,
    #[serde(default)]
    pub optional_signals: Option<Vec<serde_json::Value>>,
    #[serde(default)]
    pub verify: Option<serde_json::Value>,
    #[serde(default)]
    pub gates: Option<serde_json::Value>,
    #[serde(default)]
    pub s_module_hints: Option<serde_json::Value>,
    pub confidence_score: f64,
    pub confidence_level: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct LogEventSchema {
    pub event_type: String,
    pub producer: String,
    pub when: String,
    pub payload: serde_json::Value,
    pub severity: String,
    #[serde(default)]
    pub sinks: Option<Vec<String>>,
    #[serde(default)]
    pub links: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ResponseEnvelope {
    pub answer: serde_json::Value,
    pub evidence: serde_json::Value,
    pub self_check: serde_json::Value,
    pub decision_ref: serde_json::Value,
    pub audit: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct StructuredOutput {
    pub artifact_type: String,
    pub content: String,
    pub compliance_report: serde_json::Value,
    pub artifact_meta: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct MemoryRecord {
    pub record_id: String,
    pub project_id: String,
    pub scope: String,
    pub memory_type: String,
    pub content_summary: String,
    pub created_at: String,
    pub policy_decision: String,
    #[serde(default)]
    pub ttl: Option<String>,
    #[serde(default)]
    pub tags: Option<Vec<String>>,
    #[serde(default)]
    pub source_refs: Option<Vec<String>>,
    #[serde(default)]
    pub masked: Option<bool>,
    #[serde(default)]
    pub activation_state: Option<String>,
    #[serde(default)]
    pub version: Option<String>,
    #[serde(default)]
    pub procedure_id: Option<String>,
    #[serde(default)]
    pub target_scope: Option<String>,
    #[serde(default)]
    pub trigger_conditions: Option<String>,
    #[serde(default)]
    pub steps: Option<Vec<String>>,
    #[serde(default)]
    pub required_tools: Option<Vec<String>>,
    #[serde(default)]
    pub safety_notes: Option<String>,
    #[serde(default)]
    pub provenance: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct SourceQoD {
    pub source_id: String,
    pub project_id: String,
    pub qod_score: f64,
    pub freshness: f64,
    pub reliability: f64,
    pub completeness: f64,
    pub computed_at: String,
    #[serde(default)]
    pub scope: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct PolicyCheck {
    pub check_id: String,
    pub decision: String,
    pub reasons: Vec<String>,
    pub rule_refs: Vec<String>,
    pub detected_sensitive_types: Vec<String>,
    #[serde(default)]
    pub fallback_id: Option<String>,
    #[serde(default)]
    pub required_approval_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ApprovalSchema {
    pub approval_id: String,
    pub approval_stage: String,
    pub requester: String,
    pub scope: String,
    pub description: String,
    pub expires_at: String,
    pub status: String,
    pub decided_by: String,
    #[serde(default)]
    pub risk_level: Option<String>,
    #[serde(default)]
    pub cost_snapshot: Option<serde_json::Value>,
    #[serde(default)]
    pub policy_snapshot: Option<serde_json::Value>,
    #[serde(default)]
    pub audit_trace_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct CostBudget {
    pub budget_id: String,
    pub mode: String,
    pub daily_limit: i64,
    pub monthly_limit: i64,
    pub used_today: i64,
    pub used_month: i64,
    #[serde(default)]
    pub forecast: Option<f64>,
    #[serde(default)]
    pub actual: Option<f64>,
    #[serde(default)]
    pub block_on_exceed: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct DownshiftSchema {
    pub warn_threshold_percent: i64,
    pub block_threshold_percent: i64,
    pub trigger_type: String,
    pub near_action: String,
    pub exceed_action: String,
    pub main_requires_approval: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NodeCapabilityProfile {
    pub node_id: String,
    pub required_tools: Vec<String>,
    pub risk_class: String,
    pub cost_class: String,
    pub required_gates: Vec<String>,
    #[serde(default)]
    pub optional_tools: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NodeRequestEnvelope {
    pub request_id: String,
    pub project_id: String,
    pub session_id: String,
    pub node_id: String,
    pub intent_summary: String,
    pub constraints: serde_json::Value,
    pub trace_id: String,
    #[serde(default)]
    pub policy_snapshot_id: Option<String>,
    #[serde(default)]
    pub budget_snapshot_id: Option<String>,
    #[serde(default)]
    pub evidence_refs: Option<Vec<String>>,
    #[serde(default)]
    pub decision_id: Option<String>,
    #[serde(default)]
    pub ui_hints: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NodeResponseEnvelope {
    pub trace_id: String,
    pub node_id: String,
    pub domain: String,
    pub inputs: serde_json::Value,
    pub outputs: serde_json::Value,
    pub status: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ToolCallRegistry {
    pub tool_id: String,
    pub node_id: String,
    pub risk_class: String,
    pub auth_method: String,
    pub enabled: bool,
    #[serde(default)]
    pub mcp_endpoint: Option<String>,
    #[serde(default)]
    pub rate_limit: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct MCPBridgeLayer {
    pub bridge_id: String,
    pub node_id: String,
    pub transport: String,
    pub base_url: String,
    #[serde(default)]
    pub discovered_tools: Option<Vec<String>>,
    #[serde(default)]
    pub auth_config: Option<serde_json::Value>,
    #[serde(default)]
    pub health_check_interval_sec: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ToolRegistryEntry {
    pub tool_id: String,
    pub category: String,
    pub adapter_id: String,
    pub risk_class: String,
    pub cost_class: String,
    pub required_gates: Vec<String>,
    #[serde(default)]
    pub outputs: Option<Vec<String>>,
    #[serde(default)]
    pub notes: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct BrainAdapterResponse {
    pub output_text: String,
    pub evidence_summary: String,
    pub cost_used_estimate: serde_json::Value,
    pub warnings: Vec<String>,
    pub trace_id: String,
    #[serde(default)]
    pub tool_calls: Option<Vec<serde_json::Value>>,
    #[serde(default)]
    pub qod_hint: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct WorkflowStage {
    pub stage_id: String,
    pub stage_name: String,
    pub description: String,
    #[serde(default)]
    pub sub_stages: Option<Vec<serde_json::Value>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct WorkflowOutput {
    pub user_response: String,
    pub evidence_summary: String,
    pub log_report: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct FailureReport {
    pub failure_cause: String,
    pub evidence_gap: String,
    pub risk_detected: serde_json::Value,
    pub improvement_hint: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct GuardrailsCheck {
    pub check_id: String,
    pub trace_id: String,
    pub layer1_nemo: serde_json::Value,
    pub layer2_guardrails_ai: serde_json::Value,
    pub layer3_llamaguard: serde_json::Value,
    pub overall_decision: String,
    #[serde(default)]
    pub blocked_by: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct RBACRole {
    pub role: String,
    pub permissions: Vec<String>,
    pub description: String,
    pub max_autonomy_level: String,
    pub p2_access: bool,
    #[serde(default)]
    pub cost_approval_limit: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct AutonomyLevelSchema {
    pub level: String,
    pub name: String,
    pub description: String,
    pub auto_execute: bool,
    pub notification_required: bool,
    pub approval_required: bool,
    #[serde(default)]
    pub allowed_domains: Option<Vec<String>>,
}

/// 왕복 검증(A20 Rust 구간): JSON → 구조체(deny_unknown_fields) → JSON → 구조체 동일성.
/// 미지 필드/타입 불일치는 역직렬화 에러로 거부된다(extra='forbid' 등가).
pub fn roundtrip_validate(name: &str, json: &str) -> Result<String, String> {
    macro_rules! rt {
        ($t:ty) => {{
            let v: $t = serde_json::from_str(json).map_err(|e| e.to_string())?;
            let s = serde_json::to_string(&v).map_err(|e| e.to_string())?;
            let v2: $t = serde_json::from_str(&s).map_err(|e| e.to_string())?;
            if v != v2 { return Err(format!("{}: 왕복 동일성 불일치", name)); }
            Ok(s)
        }};
    }
    match name {
        "IntentFrame" => rt!(IntentFrame),
        "EvidencePack" => rt!(EvidencePack),
        "DecisionSchema" => rt!(DecisionSchema),
        "LogEventSchema" => rt!(LogEventSchema),
        "ResponseEnvelope" => rt!(ResponseEnvelope),
        "StructuredOutput" => rt!(StructuredOutput),
        "MemoryRecord" => rt!(MemoryRecord),
        "SourceQoD" => rt!(SourceQoD),
        "PolicyCheck" => rt!(PolicyCheck),
        "ApprovalSchema" => rt!(ApprovalSchema),
        "CostBudget" => rt!(CostBudget),
        "DownshiftSchema" => rt!(DownshiftSchema),
        "NodeCapabilityProfile" => rt!(NodeCapabilityProfile),
        "NodeRequestEnvelope" => rt!(NodeRequestEnvelope),
        "NodeResponseEnvelope" => rt!(NodeResponseEnvelope),
        "ToolCallRegistry" => rt!(ToolCallRegistry),
        "MCPBridgeLayer" => rt!(MCPBridgeLayer),
        "ToolRegistryEntry" => rt!(ToolRegistryEntry),
        "BrainAdapterResponse" => rt!(BrainAdapterResponse),
        "WorkflowStage" => rt!(WorkflowStage),
        "WorkflowOutput" => rt!(WorkflowOutput),
        "FailureReport" => rt!(FailureReport),
        "GuardrailsCheck" => rt!(GuardrailsCheck),
        "RBACRole" => rt!(RBACRole),
        "AutonomyLevelSchema" => rt!(AutonomyLevelSchema),
        _ => Err(format!("unknown model: {}", name)),
    }
}

pub const MODEL_NAMES: &[&str] = &["IntentFrame", "EvidencePack", "DecisionSchema", "LogEventSchema", "ResponseEnvelope", "StructuredOutput", "MemoryRecord", "SourceQoD", "PolicyCheck", "ApprovalSchema", "CostBudget", "DownshiftSchema", "NodeCapabilityProfile", "NodeRequestEnvelope", "NodeResponseEnvelope", "ToolCallRegistry", "MCPBridgeLayer", "ToolRegistryEntry", "BrainAdapterResponse", "WorkflowStage", "WorkflowOutput", "FailureReport", "GuardrailsCheck", "RBACRole", "AutonomyLevelSchema"];
