"""A20 타입 동기화 — Pydantic(정본) → JSON Schema → TypeScript(Zod) + serde(Rust) 자동 생성 (DEC-006).

생성물 (직접 수정 금지 — A20 규칙 3):
  shared/types/json_schema/<Model>.schema.json  (25종)
  shared/types/vamos.ts                          (Zod 스키마 + TS 타입 25종)
  shared/types/validate_roundtrip.mjs            (무의존 Node JSON-Schema 검증기 — 왕복 테스트 TS측)
  src-tauri/src/models/generated.rs              (serde 구조체 25종 + roundtrip_validate — A20 Rust 구간)

serde(Rust)는 P4-2에서 활성화(PHASE4-DEC-005 §5). 왕복 테스트 4파일 경로 =
Python→JSON Schema→serde(Rust 컴파일 검증)→TS(Node 검증)→Python.

사용: python scripts/generate_types.py
"""

from __future__ import annotations

import io
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from vamos_core.schemas.contracts import ALL_MODELS  # noqa: E402

OUT = ROOT / "shared" / "types"
SCHEMA_DIR = OUT / "json_schema"
SCHEMA_DIR.mkdir(parents=True, exist_ok=True)


def write(path: pathlib.Path, content: str) -> None:
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)


# ── 1) Pydantic → JSON Schema ───────────────────────────────────────────────

schemas: dict[str, dict] = {}
for model in ALL_MODELS:
    schema = model.model_json_schema()
    schemas[model.__name__] = schema
    write(SCHEMA_DIR / f"{model.__name__}.schema.json",
          json.dumps(schema, ensure_ascii=False, indent=2) + "\n")
print(f"[1/3] JSON Schema {len(schemas)}종 → shared/types/json_schema/")


# ── 2) JSON Schema → TypeScript (Zod) ───────────────────────────────────────

def zod_of(prop: dict) -> str:
    """JSON Schema property → Zod 표현 (본 프로젝트 스키마 부분집합)."""
    if "anyOf" in prop:  # Pydantic optional: anyOf [T, null]
        variants = [v for v in prop["anyOf"] if v.get("type") != "null"]
        nullable = len(variants) != len(prop["anyOf"])
        inner = zod_of(variants[0]) if variants else "z.any()"
        return f"{inner}.nullable()" if nullable else inner
    if "enum" in prop:
        vals = ", ".join(json.dumps(v, ensure_ascii=False) for v in prop["enum"])
        return f"z.enum([{vals}])"
    if "const" in prop:
        return f"z.literal({json.dumps(prop['const'], ensure_ascii=False)})"
    t = prop.get("type")
    if t == "string":
        return "z.string()"
    if t == "integer":
        return "z.number().int()"
    if t == "number":
        expr = "z.number()"
        if "minimum" in prop:
            expr += f".min({prop['minimum']})"
        if "maximum" in prop:
            expr += f".max({prop['maximum']})"
        return expr
    if t == "boolean":
        return "z.boolean()"
    if t == "array":
        items = prop.get("items")
        return f"z.array({zod_of(items) if items else 'z.any()'})"
    if t == "object":
        return "z.record(z.any())"
    return "z.any()"


ts_parts = [
    "// AUTO-GENERATED by scripts/generate_types.py — DO NOT EDIT (A20/DEC-006).",
    "// 정본: backend/vamos_core/schemas/contracts.py (Pydantic v2). 변경은 Pydantic에서 시작.",
    'import { z } from "zod";',
    "",
]
for name, schema in schemas.items():
    required = set(schema.get("required", []))
    lines = [f"export const {name}Schema = z.object({{"]
    for prop_name, prop in schema.get("properties", {}).items():
        expr = zod_of(prop)
        if prop_name not in required:
            expr += ".optional()"
        lines.append(f"  {prop_name}: {expr},")
    lines.append("}).strict();  // extra='forbid'")
    lines.append(f"export type {name} = z.infer<typeof {name}Schema>;")
    lines.append("")
    ts_parts.append("\n".join(lines))
write(OUT / "vamos.ts", "\n".join(ts_parts))
print(f"[2/3] Zod/TS {len(schemas)}종 → shared/types/vamos.ts")


# ── 3) 무의존 Node 검증기 (왕복 테스트 TS측 — zod 미설치 환경 대응) ─────────

VALIDATOR_MJS = r"""// AUTO-GENERATED by scripts/generate_types.py — DO NOT EDIT (A20/DEC-006).
// 무의존 JSON-Schema(부분집합) 검증기: 왕복 테스트의 TS(Node)측 단계.
// 사용: node validate_roundtrip.mjs <instances.json>
//   instances.json = {"ModelName": {...instance...}, ...}
import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemaDir = join(here, "json_schema");

function checkType(v, t) {
  switch (t) {
    case "string": return typeof v === "string";
    case "integer": return typeof v === "number" && Number.isInteger(v);
    case "number": return typeof v === "number";
    case "boolean": return typeof v === "boolean";
    case "array": return Array.isArray(v);
    case "object": return v !== null && typeof v === "object" && !Array.isArray(v);
    case "null": return v === null;
    default: return true;
  }
}

function validate(value, schema, path, errors) {
  if (!schema || Object.keys(schema).length === 0) return;
  if (schema.anyOf) {
    const pre = errors.length;
    for (const sub of schema.anyOf) {
      const trial = [];
      validate(value, sub, path, trial);
      if (trial.length === 0) return;
    }
    errors.push(`${path}: anyOf 전 분기 불일치`);
    return;
  }
  if (schema.enum && !schema.enum.includes(value)) {
    errors.push(`${path}: enum 위반 (${JSON.stringify(value)})`);
    return;
  }
  if (schema.type && !checkType(value, schema.type)) {
    errors.push(`${path}: 타입 ${schema.type} 위반`);
    return;
  }
  if (schema.type === "number" || schema.type === "integer") {
    if (schema.minimum !== undefined && value < schema.minimum) errors.push(`${path}: minimum 위반`);
    if (schema.maximum !== undefined && value > schema.maximum) errors.push(`${path}: maximum 위반`);
  }
  if (schema.type === "array" && schema.items) {
    value.forEach((item, i) => validate(item, schema.items, `${path}[${i}]`, errors));
  }
  if (schema.type === "object" && schema.properties) {
    for (const req of schema.required ?? []) {
      if (!(req in value)) errors.push(`${path}.${req}: 필수 필드 누락`);
    }
    for (const [k, v] of Object.entries(value)) {
      if (k in schema.properties) {
        validate(v, schema.properties[k], `${path}.${k}`, errors);
      } else if (schema.additionalProperties === false) {
        errors.push(`${path}.${k}: additionalProperties=false 위반 (extra='forbid')`);
      }
    }
  }
}

const instances = JSON.parse(readFileSync(process.argv[2], "utf-8"));
const available = new Set(readdirSync(schemaDir).map((f) => f.replace(".schema.json", "")));
let failed = 0;
const out = {};
for (const [name, instance] of Object.entries(instances)) {
  if (!available.has(name)) { console.error(`SKIP ${name}: 스키마 파일 없음`); failed++; continue; }
  const schema = JSON.parse(readFileSync(join(schemaDir, `${name}.schema.json`), "utf-8"));
  const errors = [];
  validate(instance, schema, name, errors);
  if (errors.length) { failed++; console.error(`FAIL ${name}:\n  ` + errors.join("\n  ")); }
  out[name] = instance; // TS측 통과 인스턴스를 그대로 반환 (Python 재파싱 입력)
}
if (failed) { console.error(`TS-side validation FAILED: ${failed}`); process.exit(1); }
console.log(JSON.stringify(out));
"""
write(OUT / "validate_roundtrip.mjs", VALIDATOR_MJS)
print("[3/4] Node 검증기 → shared/types/validate_roundtrip.mjs")


# ── 4) JSON Schema → serde(Rust) 구조체 (A20 Rust 구간 — DEC-005 §5) ──────────

RUST_OUT = ROOT / "src-tauri" / "src" / "models"


def rust_base(prop: dict) -> tuple[str, bool]:
    """JSON Schema property → (Rust 타입, nullable). 본 프로젝트 스키마 부분집합."""
    if "anyOf" in prop:  # Pydantic optional: anyOf [T, null]
        variants = [v for v in prop["anyOf"] if v.get("type") != "null"]
        nullable = len(variants) != len(prop["anyOf"])
        inner, _ = rust_base(variants[0]) if variants else ("serde_json::Value", False)
        return inner, nullable
    if "enum" in prop or "const" in prop:
        return "String", False  # Literal → String (deny_unknown_fields가 구조 핵심; V0 최소)
    t = prop.get("type")
    if t == "string":
        return "String", False
    if t == "integer":
        return "i64", False
    if t == "number":
        return "f64", False
    if t == "boolean":
        return "bool", False
    if t == "array":
        items = prop.get("items")
        if items and items.get("type") in {"string", "integer", "number", "boolean"}:
            inner, _ = rust_base(items)
            return f"Vec<{inner}>", False
        return "Vec<serde_json::Value>", False  # list[dict]/list[Any]
    if t == "object":
        return "serde_json::Value", False
    return "serde_json::Value", False


rust_parts = [
    "// AUTO-GENERATED by scripts/generate_types.py — DO NOT EDIT (A20/DEC-006).",
    "// 정본: backend/vamos_core/schemas/contracts.py (Pydantic v2). 변경은 Pydantic에서 시작.",
    "// deny_unknown_fields = Pydantic extra='forbid' 등가 (A20 규칙 2).",
    "#![allow(non_snake_case, dead_code)]",
    "use serde::{Deserialize, Serialize};",
    "",
]
for name, schema in schemas.items():
    required = set(schema.get("required", []))
    lines = [
        "#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]",
        "#[serde(deny_unknown_fields)]",
        f"pub struct {name} {{",
    ]
    for prop_name, prop in schema.get("properties", {}).items():
        base, nullable = rust_base(prop)
        optional = nullable or (prop_name not in required)
        ty = f"Option<{base}>" if optional else base
        if optional:
            lines.append("    #[serde(default)]")
        lines.append(f"    pub {prop_name}: {ty},")
    lines.append("}")
    lines.append("")
    rust_parts.append("\n".join(lines))

# 왕복 검증 디스패처: name → 구조체 역직렬화 → 재직렬화 → 재역직렬화 동일성(PartialEq).
rt_arms = "\n".join(
    f'        "{name}" => rt!({name}),' for name in schemas
)
names_arr = ", ".join(f'"{name}"' for name in schemas)
rust_parts.append(
    "/// 왕복 검증(A20 Rust 구간): JSON → 구조체(deny_unknown_fields) → JSON → 구조체 동일성.\n"
    "/// 미지 필드/타입 불일치는 역직렬화 에러로 거부된다(extra='forbid' 등가).\n"
    "pub fn roundtrip_validate(name: &str, json: &str) -> Result<String, String> {\n"
    "    macro_rules! rt {\n"
    "        ($t:ty) => {{\n"
    "            let v: $t = serde_json::from_str(json).map_err(|e| e.to_string())?;\n"
    "            let s = serde_json::to_string(&v).map_err(|e| e.to_string())?;\n"
    "            let v2: $t = serde_json::from_str(&s).map_err(|e| e.to_string())?;\n"
    '            if v != v2 { return Err(format!("{}: 왕복 동일성 불일치", name)); }\n'
    "            Ok(s)\n"
    "        }};\n"
    "    }\n"
    "    match name {\n"
    f"{rt_arms}\n"
    '        _ => Err(format!("unknown model: {}", name)),\n'
    "    }\n"
    "}\n\n"
    f"pub const MODEL_NAMES: &[&str] = &[{names_arr}];"
)
RUST_OUT.mkdir(parents=True, exist_ok=True)
write(RUST_OUT / "generated.rs", "\n".join(rust_parts) + "\n")
print(f"[4/4] serde(Rust) {len(schemas)}종 → src-tauri/src/models/generated.rs")
print(f"✅ generate_types 완료 — 모델 {len(schemas)}종 (JSON Schema · TS · Node검증기 · serde)")
